apiVersion: v1
kind: BuildConfig
metadata:
  name: 'employee-service-development'
  namespace: ci-cd
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "employee-service", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    - type: GitHub
      github:
        secret: ${GITHUB_TRIGGER_SECRET}
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'git@github.com:in-the-keyhole/khs-employee-service'
      ref: openshift-cicd
    sourceSecret:
      name: github-secret
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
parameters:
- description: GitHub Trigger Secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GITHUB_TRIGGER_SECRET