apiVersion: v1
kind: Template
metadata:
  name: mysql-employee
  annotations:
    description: MySQL for the reference employee-service
    tags: mysql, db, employee
objects:

# DEPLOYMENT CONFIG
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: mysql-employee
    labels:
      app: mysql-employee
      template: mysql-ephemeral-template
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - mysql
          from:
            kind: ImageStreamTag
            namespace: openshift
            name: 'mysql:5.7'
      - type: ConfigChange
    replicas: 1
    test: false
    selector:
      name: mysql-employee
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: mysql-employee
      spec:
        volumes:
          - name: mysql-employee-data
            emptyDir: {}
        containers:
          - name: mysql
            ports:
              - containerPort: 3306
                protocol: TCP
            env:
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: mysql-employee
                    key: database-user
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-employee
                    key: database-password
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-employee
                    key: database-root-password
              - name: MYSQL_DATABASE
                value: employee
            resources:
              limits:
                memory: 512Mi
            volumeMounts:
              - name: mysql-employee-data
                mountPath: /var/lib/mysql/data
            livenessProbe:
              tcpSocket:
                port: 3306
              initialDelaySeconds: 30
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            readinessProbe:
              exec:
                command:
                  - /bin/sh
                  - '-i'
                  - '-c'
                  - >-
                    MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER
                    -D $MYSQL_DATABASE -e 'SELECT 1'
              initialDelaySeconds: 5
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePath: /dev/termination-log
            imagePullPolicy: IfNotPresent
            securityContext:
              capabilities: {}
              privileged: false
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}

# SERVICE  
- apiVersion: v1
  kind: Service
  metadata:
    name: mysql-employee
    labels:
      app: mysql-employee
      template: mysql-ephemeral-template
    annotations:
      template.openshift.io/expose-uri: 'mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}'
  spec:
    ports:
      - name: mysql
        protocol: TCP
        port: 3306
        targetPort: 3306
    selector:
      name: mysql-employee
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {}

# SECRET   
- apiVersion: v1
  kind: Secret
  metadata:
    name: mysql-employee
    labels:
      app: mysql-employee
      template: mysql-ephemeral-template
    annotations:
      template.openshift.io/expose-password: '{.data[''database-password'']}'
      template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
      template.openshift.io/expose-username: '{.data[''database-user'']}'
  data:
    database-password: cGFzc3dvcmQ=
    database-root-password: cGFzc3dvcmQ=
    database-user: YXBwdXNlcg==
  type: Opaque

    