swagger: '2.0'
info:
  description: Swagger for KHS Employee REST API. You can find out more about this project at https://in-the-keyhole/khs-employee-service
  version: v1
  title: Swagger for KHS Employee REST API
host: 'localhost:8082'
tags:
  - name: employees
schemes:
  - http
paths:
  /employees:
    get:
      tags:
        - employees
      summary: List of Employees
      description: Returns all Employees
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: Successful retrieval of Employees
          schema:
            type: array
            items:
              $ref: '#/definitions/Employee'
        '404':
          description: No Employees Found
        default:
          description: unexpected error
    post:
      tags:
        - employees
      summary: Add a new Employee
      description: ''
      operationId: addEmployee
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Employee object to be added
          required: true
          schema:
            $ref: '#/definitions/Employee'
      responses:
        '405':
          description: Invalid input
  '/employees/{id}':
    get:
      tags:
        - employees
      summary: Find Employee by ID
      description: Returns a single Employee
      operationId: getEmployee
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of Employee to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Successfull retrieval of Employee
          schema:
            $ref: '#/definitions/Employee'
        '404':
          description: Employee not found
        default:
          description: unexpected error
    put:
      tags:
        - employees
      summary: Update an existing Employee
      description: ''
      operationId: updateEmployee
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of Employee that needs to be updated
          required: true
          type: integer
          format: int64
        - name: firstname
          in: formData
          description: Updated firstname of the Employee
          required: false
          type: string
        - name: lastname
          in: formData
          description: Updated lastname for the Employee
          required: false
          type: string
        - name: email
          in: formData
          description: Updated email for the Employee
          required: false
          type: string
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Employee not found
        '405':
          description: Validation exception
    delete:
      tags:
        - employees
      summary: Deletes an Employee
      description: ''
      operationId: deleteEmployee
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Employee ID to delete
          required: true
          type: integer
          format: int64
      responses:
        '404':
          description: Employee not found
        default:
          description: an error occurred
definitions:
  Employee:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
        example: '1'
      firstname:
        type: string
        example: john
      lastname:
        type: string
        example: doe
      email:
        type: string
        example: johndoe@email.com
    xml:
      name: Employee
